[project]
name = "nahpu-icon-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fonttools>=4.63.0",
    "svgelements>=1.9.6",
    "ufo2ft>=3.7.3",
    "ufolib2>=0.18.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]